---
- name: create /var/web directory
  file:
    path: /var/web
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: create /var/log directory
  file:
    path: /var/log
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"


- name: create /etc/letsencrypt/live/ directory
  file:
    path: /etc/letsencrypt/live
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

