---
- name: Create /var/web directory
  file:
    path: /var/web
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Create /var/log directory
  file:
    path: /var/log
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Create subdirectories inside /var/web
  file:
    path: "/var/web/{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
  loop:
    - dokuwiki
    - supersausage
    - wojciklaw
    - sandrako
