##
# install base utils packages
##
---
- name: Install utils packages
  apt: pkg=ntp state=present update-cache=yes
  with_items:
    - htop
    - wget
    - top
    - ntp
    - dig
    - nslookup
  tags:
    - packages

- name: install image libraries
  apt: name={{ item }} state=present
  with_items:
    - libjpeg8-dev
    - zlib1g-dev
    - libtiff-dev
    - libfreetype6
    - libfreetype6-dev
    - libwebp-dev
    - libopenjp2-7-dev
    - libopenjp2-7-dev
  run_once: true

