---
- name: update apt repo
  action: apt update-cache=yes

- name: install php-fpm
  action: apt name=php-fpm state=present

# https://github.com/dokuwiki/dokuwiki/issues/3955
# see ?do=check, mb_string extension is available and will be used (should be present)
- name: install php-mbstring to make search fast
  action: apt name=php-mbstring state=present

- name: Copy php-fpm-pool.conf to /etc/php/7.0/fpm/pool.d/ubuntu.conf
  copy:
    src: "files/php-fpm-pool.conf"
    dest: "/etc/php/8.1/fpm/pool.d/ubuntu.conf"

- name: service php8.1-fpm
  action: service name=php8.1-fpm state=restarted
