---
- name: update apt repo
  action: apt update-cache=yes

- name: install php-fpm
  action: apt name=php-fpm state=present

- name: Copy php-fpm-pool.conf to /etc/php/7.0/fpm/pool.d/your_user.conf
  copy:
    src: "files/php-fpm-pool.conf"
    dest: "/etc/php/8.1/fpm/pool.d/your_user.conf"

# No more service?
#- name: service php-fpm
#  action: service name=php-fpm state=restarted
