---
- name: install py libraries
  apt: name={{ item }} state=present
  with_items:
    - python3-pip
    - build-essential
  run_once: true


- name: install certbot-nginx
  pip:
    name:
      - certbot-nginx
      - virtualenv
    executable: pip3
