---
# https://www.digitalocean.com/community/tutorials/how-to-use-certbot-standalone-mode-to-retrieve-let-s-encrypt-ssl-certificates-on-ubuntu-22-04#step-4-handling-certbot-automatic-renewals
- name: install certbot-nginx
  pip:
    name:
      - certbot
      - certbot-nginx
      - virtualenv
    executable: pip3

- name: get certificate directories
  set_fact:
    cert_dirs: "{{ lookup('fileglob', '/etc/letsencrypt/live/*/') }}"

- name: configure certbot with existing certificates
  command: >
    certbot --nginx certonly
    --cert-name {{ item.cert_name }}
    --cert-path {{ item.cert_path }}/fullchain.pem
    --key-path {{ item.cert_path }}/privkey.pem
  loop: "{{ cert_dirs }}"
  loop_control:
    loop_var: item

- name: set up cron job for certificate renewal
  cron:
    name: "renew Let's Encrypt ssl certs"
    minute: "0"
    hour: "0"
    day: "*/2"  # Run every other day - only renews if cert 30 days old
    job: "/usr/bin/certbot renew --quiet"

- name: restart Nginx to apply changes
  service:
    name: nginx
    state: restarted