---
- name: update apt cache
  apt:
    update_cache: yes

- name: install necessary packages
  apt:
    name: ['nginx', 'php-fpm', 'php-xml', 'php-gd', 'tar']
    state: present

- name: create /var/web/dokuwiki dir
  file:
    path: /var/web/dokuwiki
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: download DokuWiki
  get_url:
    url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
    dest: /tmp/dokuwiki.tgz

- name: extract DokuWiki archive
  unarchive:
    src: /tmp/dokuwiki.tgz
    dest: /var/web/dokuwiki/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: change ownership of DokuWiki files
  file:
    path: /var/web/dokuwiki
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    recurse: yes

# also done in 8sites.yml
- name: copy dokuwiki nginx conf
  copy:
    src: "files/nginx/dokuwiki.conf"
    dest: "/etc/nginx/conf.d/dokuwiki.conf"

- name: restart nginx
  service:
    name: nginx
    state: restarted