---
##
# This is a python packages
##

- name: install python-dev and tools packages
  action: apt name=python-dev state=present
  with_items:
    - python-pip
    - build-essential
    - openssh-server
    - python-imaging
  run_once: true
  notify:
    - pip upgmcrade setuptools


- name: install certbot-nginx
  pip:
    name: certbot-nginx
    executable: pip3