# AMI Search in AMI Catalogue in EC2/Images, https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#AMICatalog:
# Latest instance versions: https://console.aws.amazon.com/ec2/
aws_defaults:  # this is a dict of dicts
  aws_region: us-east-1   # eu-west-1
  ami_id: ami-080e1f13689e07408 #  Ubuntu LTS 22.04.x
#  ami_id: ami-058bd2d568351da34  # Debian 12
  instance_type: t2.nano  # slightly more mem vs t3.nano due to kernel size
  aws_key_pair: deli-cms
  security_group: launch-wizard-1
  aws_zone: us-east-1a
  name: "app_server3"
  vpc_subnet_id: subnet-eee16e8b

# user used by ansible to connect to instance (default is ec2-user aws linux, ubuntu for ubuntu)
# debian is admin but playbook would need to change to use debian
ansible_ssh_user: ubuntu
#ansible_ssh_user: admin
